# Site settings
title: "GNUnicorn"
email: ben@gnunicorn.org
description: > # test
            Freelance OpenSource Software Architect and Developer
            I design, build and supervise the building of software (systems).
            Sometimes for clients, often times on my own, whenever possible as
            OpenSource. I care about good design in both, the User Experience
            and backend architecture and infrastructure. And I write about all
            this stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gnunicorn.org" # the base hostname & protocol for your site
twitter_username: gnunicornBen
github_username:  gnunicorn


timezone: "Europe/Berlin"
LSI: true

permalink: /blog/:title/
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Build settings
markdown: kramdown

exclude:
  - .bundle
  - vendor

gems:
- jekyll-redirect-from
- jekyll-sitemap
